# Generated by Django 4.2.3 on 2024-01-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='id',
            new_name='Sid',
        ),
    ]
