# Generated by Django 4.2.3 on 2024-02-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0002_rename_id_sample_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('HR', 'HR'), ('Software Engineer', 'SE'), ('Project lead', 'Project lead')], max_length=30)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleApp.sample')),
            ],
        ),
    ]
